print("ax^2+bx+c")
a = float(input("Enter first number:"))
b = float(input("Enter second number:"))
c = float(input("Enter third number:"))
x1 = (((-b) + (b**2-4*a*c))/2*a)
x2 = (((-b) - (b**2-4*a*c))/2*a)
print("Result:", x1 ,";", x2)
